### ISSUE TITLE
What distinguishes names from variables?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [facebookincubator/retrie#12]
The README describes how to rewrite `map a . map b` as `map (a . b)` everywhere it's found. Somehow Retrie understands that `a` and `b` are variables but `map` is not -- so it would rewrite `map foo . map bar` but not `foo a . foo b`.

What if I had a function `foo`, and I wanted to rewrite `map foo . map b` as `map (foo . b)`, for any value of `b`, but leave untouched any `map a . map b` in which `a` is not equal to `foo`?

**Comment by watashi** [comment]
Everything is "name" expect those explicitly introduce by `forall`.
So `forall b.  map foo . map b = map (foo . b)` will do what you want while `forall foo b. map foo . map b = map (foo . b)` will rewrite `map x . map y` to `map (x . y)` as well.

**Comment by JeffreyBenjaminBrown** [comment]
Ah of course. Thanks!

So if I wanted to rename foo to baz, I would just call the following?
```
retrie --adhoc "foo = baz"
```

What if two packages export the name "foo", and I only want to rename one of them?

**Comment by JeffreyBenjaminBrown** [comment]
And what about puns? If a type and a constructor share a name, can you rename one without naming the other?

**Comment by watashi** [comment]
`--adhoc` is a convenient way of specifying `--rule-forward`, which only applies to expressions, not types.
You need separate `--type-forward` to rewrite types.

**Comment by xich** [comment]
> And what about puns? If a type and a constructor share a name, can you rename one without naming the other?

Types and constructors are in different namespaces, so require different rewrites (`--type-forward` and `--rule-forward`/`--adhoc`, respectively).

> What if two packages export the name "foo", and I only want to rename one of them?

This is the biggest limitation of retrie (which I should really call out better in the README, I'll fix that). It works on parsed source only (not renamed source), so it only has local scoping information. It could distinguish an imported `foo` from a locally-bound `foo`, but not two `foo`s defined at the top-level of two different modules.

I have some ideas about fixing this limitation (#10), but no implementation yet.

In practice, this hasn't been a huge problem because the two `foo`s rarely have the same type, and the type system will catch it and you can just revert the change with version control. Typeclass instance methods are obviously the big exception to that, but in that case you also need the type, and we haven't really tried to tackle typeclasses (e.g. to unfold an instance method and have the proper implementation body chosen).
